# syntax = docker/dockerfile:experimental
FROM rosenblattai/fraxses-automl:latest

COPY requirements/serve.txt requirements.txt
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements.txt

ENTRYPOINT [ "python", "serve.py"]