# syntax = docker/dockerfile:experimental
FROM rosenblattai/fraxses-automl:latest

COPY requirements/tune.txt requirements.txt
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements.txt

COPY automl/tune.py tune.py

ENTRYPOINT ["python", "tune.py"]
